services:
    listener.security:
        class: Beloop\Component\Analytics\EventListener\SecurityListener
        arguments: ["@beloop.analytics_manager", "@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    listener.request_response:
        class: Beloop\Component\Analytics\EventListener\RequestListener
        arguments: ["@doctrine.orm.analytics_entity_manager", "@security.token_storage"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }